service: majestic-stars
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${env:AWS_PROFILE}
  region: eu-north-1
  iam:
    role: ${env:LAMBDA_ROLE}
  deploymentMethod: direct
  environment:
    MONGO_URL: ${env:MONGO_URL}

useDotenv: true
plugins:
  - serverless-webpack
package:
  individually: true
custom:
  webpack:
    webpackConfig: 'webpack.config.cjs'

functions:
  register:
    handler: src/functions/auth/register.handler
    events:
      - httpApi: 'POST /api/register'

  login:
    handler: src/functions/auth/login.handler
    events:
      - httpApi: 'POST /api/login'
  addMeetup: 
    handler: src/functions/meetups/addMeetup.handler
    events:
      - httpApi: 'POST /api/meetups'
  getMeetups:
    handler: src/functions/meetups/getMeetups.handler
    events:
      - httpApi: 'GET /api/meetups'
  searchMeetups:
    handler: src/functions/meetups/searchMeetups.handler
    events:
      - httpApi: 'GET /api/meetups/search'
  addCommentAndRating:
    handler: src/functions/meetups/addCommentAndRating.handler
    events:
      - httpApi: 'POST /api/meetups/{meetupId}/comment'
  filterMeetups:
    handler: src/functions/meetups/filterMeetups.handler
    events:
      - httpApi: 'GET /api/meetups/filter'
