service: majestic-stars
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: ${arn:aws:iam::345653343938:user/Main_Henry}
  region: eu-north-1
  iam:
    role: ${arn:aws:iam::345653343938:role/Bonzai_groupexam}
  deploymentMethod: direct

useDotenv: true
plugins:
  - serverless-webpack
package:
  individually: true
custom:
  webpack:
    webpackConfig: 'webpack.config.cjs'

functions:
  register:
    handler: src/functions/auth/register.handler
    events:
      - httpApi: 'POST /api/register'
  login:
    handler: src/functions/auth/login.handler
    events:
      - httpApi: 'POST /api/login'